### ISSUE TITLE
Error 500 (Nancy)

### ISSUE THREAD

**Issue by jbelien** [itinero/routing-api#11]
If I use the example http://localhost:5000/belgium, everything seems to work as expected : I can click 2 points in the map and the route is calculated between those 2 points.

But if I request the API (in my browser) by going to http://localhost:5000/belgium/routing?profile=car&loc=51.218927,2.905884&loc=49.676515,5.814514 I have an error 500 from Nancy.

![image](https://user-images.githubusercontent.com/1150563/30480427-f2a8958c-9a19-11e7-8a8a-aeab757de72d.png)

When I make the same request with cURL it does work though ...

Any idea ?
Thanks !

**Comment by jbelien** [comment]
Related to #2 !

Just need to add `Accept: application/json` in the request header.

**Comment by mhosman** [comment]
Here the same problem. Not solved with Accept: application/json.

**Comment by jbelien** [comment]
@mhosman Could you give more information about your issue ?
Adding `Accept: application/json` in the request header fixes the problem.

Could you try the same request with `cURL` ?

**Comment by xivk** [comment]
@mhosman Are you sure the routerdb loaded properly? Can you post the console log output?
