### ISSUE TITLE
[RouterBaseExtensions] information - Profile(s) bicycle not cached, building cache.

### ISSUE THREAD

**Issue by relax-lee** [itinero/routing-api#13]
Hi~!
I'm using your project to build an application for riding planning. However,I got a problem,

When I send the following request to the routing-api server, an error occurs.

`http://localhost:5000/taiwan/routing?callback=itinero.JSONP.callbacks.route4&profile=bicycle&loc=24.196477,120.693312&loc=24.197671,120.690608&sort=true`

**[RouterBaseExtensions] information - Profile(s) bicycle not cached, building cache.**

RouterDb  generated using official tools
Build a RouterDb for pedestrians and bicycle and add a contracted graph for both:
`idp --read-pbf path/to/some-file.osm.pbf --pr --create-routerdb vehicles=bicycle,pedestrian --contract bicycle --contract pedestrian --write-routerdb some-file.routerdb`

**Comment by xivk** [comment]
That's not an error, the first time a profile is used a cache is built, this shouldn't be something to worry about unless it happens on every request.
